# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run test
    - name: JSDoc Action
  # You may pin to the exact commit or the version.
  # uses: andstor/jsdoc-action@2fb2b536605bdebace2b92abb0601155d5ddc688
      # You may pin to the exact commit or the version.
      # uses: andstor/jsdoc-action@2fb2b536605bdebace2b92abb0601155d5ddc688
      uses: andstor/jsdoc-action@v1.2.0
      with:
        # Source directory to build documentation from
        source_dir: "./assets/js"
        # Output folder for the generated documentation
        output_dir: "./out"
        # Recurse into subdirectories when scanning for source files
        recurse: # optional
        # The path to a JSDoc configuration file
        config_file: # optional
        # The JSDoc template to install
        template: # optional
        # This input variable is deprecated in favour of "template"
        template_name: # optional
        # The relative location of the template files within the template package
        template_dir: # optional
        # The path to a Markdown file to be used as a the front page
        front_page: # optional
